# Generated by Django 2.0.2 on 2018-03-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chargehoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrheures', models.IntegerField(max_length=2)),
                ('Matiere', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='firstname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='password',
            field=models.CharField(default='NULL', max_length=35),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.utilisateurs'),
        ),
    ]
