# Generated by Django 2.0.2 on 2018-03-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180310_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='username',
            new_name='firstname',
        ),
    ]
