# Generated by Django 2.0.2 on 2018-03-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180310_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='password',
        ),
    ]
