# Generated by Django 2.0.2 on 2018-03-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_utilisateurs_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='password',
            field=models.CharField(default='NULL', max_length=35),
        ),
    ]
